### ISSUE TITLE
Should we add the ? before the boolean ?

### ISSUE THREAD

**Issue by PabloCarreira** [mediamonks/display-advertising-docs#1]
@alandawi @mirkovw @mm-paulie 

A small intro about this ticket.
I am learning about the process to contribute to the framework. I will make the change over the documentation if we agree that is needed.

would you guys think it will help the jr people to see an example of how to add the boolean on the link?
 or maybe just add the question mark before the boolean?

https://github.com/mediamonks/display-advertising-docs/blob/6334f4f7f3b0a751fbc7933097be41b11f1cd95a/docs/guides/gsap.md?plain=1#L47

as you can see right now we have just the boolean, but no example of how to concatenate it on the link, and if the jr person doesn't know about it, it might struggle to find that.

Just let me know if you think is a good idea or not.
Thanks

**Comment by alandawi** [comment]
http://localhost:8000/?gsdevtools=true

Small change, but avoid big confusion. Good observation.

@PabloCarreira I will push some changes in the next commit and also update this code.
